### ISSUE TITLE
The branch "video-capturer-camera" possibly broken

### ISSUE THREAD

**Issue by podkovyrin** [opentok/learning-opentok-ios#2]
`OTKBasicVideoCapturer` with `AVCaptureSession` is not working:
![screen shot 2015-12-23 at 19 10 30](https://cloud.githubusercontent.com/assets/3340428/11980064/ffb9696c-a9a8-11e5-949d-257343ae5595.png)

**Comment by ObjColumnist** [comment]
I am having the same issues. Is there an easier/working way of rendering one frame to an image?

**Comment by podkovyrin** [comment]
I figured out what's the problem. This video capturer generates video output randomly :).
To get output from real camera take a look at https://github.com/opentok/opentok-ios-sdk-samples/tree/develop/2.Lets-Build-OTPublisher
