### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by danishnazir** [opentok/learning-opentok-ios#43]
Hi i would really appreciate if you can release the swift version of this demo it will be great help to beginners like me 
Thanks

**Comment by msach22** [comment]
@danishnazir Hi here's our swift samples repo: https://github.com/opentok/opentok-ios-sdk-samples-swift/

You can also check out our Basic Video Chat tutorial: https://tokbox.com/developer/tutorials/ios/swift/basic-video-chat/
