### ISSUE TITLE
video-renderer-basic crashing with iOS SDK 2.8.3

### ISSUE THREAD

**Issue by jompu** [opentok/learning-opentok-ios#6]
The video-renderer-basic branch is crashing with EXC_BAD_ACCESS.
At line 89 of file OTKCustomRenderView.m.

Xcode version: 7.3.1
Base SDK: iOS 9.3

iOS device model: iPad Air (Model A1474) 
iOS device version: 9.3.2

**Comment by jompu** [comment]
basics.step-\* branches works well.

I tried video-renderer-basic with OpenTok 2.8.1, 2.8.2 and 2.7.1 with no success.

**Comment by jompu** [comment]
Some times it will work for a while, but the video is lagging behind a lot and then crashing.

**Comment by Lucashuang0802** [comment]
@jompu do you still see this behavior using the latest iOS SDK?

**Comment by jompu** [comment]
Have not seen anymore.

**Comment by Lucashuang0802** [comment]
@jompu Thanks. Feel free to continue here if you have more questions.
